[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
dir = "src"
edition = "4.10.0"
github-organization = "ocamlpro"
kind = "both"
license = "LGPL2"
min-edition = "4.03.0"
mode = "binary"
name = "opam-bin"
sphinx-target = "docs"
synopsis = "The opam-bin tool is a simple framework to use `opam` with binary packages"
version = "0.9.4"

# keys that you could also define:
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
opam-binary is a simple framework to use `opam` with binary packages.
"""

[drom]
skip = "sphinx/_static/css/fixes.css sphinx/index.rst sphinx/conf.py docs/.nojekyll docs/index.html src/main.ml main/main.ml CHANGES.md sphinx/install.rst sphinx/about.rst .github/workflows/workflow.yml"

[dependencies]
ez_cmdliner = "0.1.0"
ez_config = "0.1.0"
ezjsonm = "1.0.0"
ocplib-json-typed = "0.7.0"
opam-file-format = "2.0.0"
re = "1.0"

[tools]
[project]
pack-modules = true

