language: c
sudo: required
install: sh .travis.install.sh
script: sh .travis.script.sh
os: linux
env:
  global:
    - DEFAULT_OCAML_VERSION=4.04.2
  matrix:
    - OCAML_VERSION=4.04.0
    - OCAML_VERSION=4.04.0 RUN_TESTS=yes
    - OCAML_VERSION=4.04.1
    - OCAML_VERSION=4.04.1 RUN_TESTS=yes
    - OCAML_VERSION=4.04.2
    - OCAML_VERSION=4.04.2 RUN_TESTS=yes
    - OCAML_VERSION=4.05.0
    - OCAML_VERSION=4.05.0 RUN_TESTS=yes
    - OCAML_VERSION=4.06.0
    - OCAML_VERSION=4.06.0 RUN_TESTS=yes
    - OCAML_VERSION=4.06.1
    - OCAML_VERSION=4.06.1 RUN_TESTS=yes
