.build and test: &build_and_test_def
  script:
    - docker run --rm -v $PWD:/override ocaml/opam2:$ocaml_version
        /override/ci-scripts/build_and_test.sh file:///override/

build and test on 4.07:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.07"

opam pin and install:
  script:
    - docker run --rm -v $PWD:/override ocaml/opam2:4.07
        /override/ci-scripts/opam-pin_and_install.sh file:///override/

build and test on 4.06:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.06"

build and test on 4.05:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.05"

build and test on 4.04:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.04"
