language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
sudo: false
services:
  - docker
env:
  global:
    - DISTRO=alpine
    - TESTS=true
    - PACKAGE="salsa20-core"
  matrix:
    - OCAML_VERSION=4.07 DEPOPTS="mirage-xen-posix"
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09 DEPOPTS="ocaml-freestanding"
notifications:
  email: false
