language: c
sudo: required
branches:
  except:
    - release
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=nocoiner
    - UPDATE_GCC_BINUTILS=1
    - OPAM_VERSION="2.0.0"
    - BISECT_ENABLE=YES
    - BISECT_SILENT=YES
    - POST_INSTALL_HOOK="make report"
  matrix:
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
os:
  - linux
# - osx
