[project]
drom-version = "0.1.0"

[project]
authors = ["Albin Coquereau"]
copyright = "Albin Coquereau"
edition = "4.10.0"
license = "Apache-2.0"
min-edition = "4.04.2"
mode = "binary"
name = "psmt2-frontend"
synopsis = "The psmt2-frontend project"
version = "0.3.0"
windows-ci = true

dev-repo = "https://github.com/OCamlPro-Coquera/psmt2-frontend/tree/next"
bug-reports = "https://github.com/OCamlPro-Coquera/psmt2-frontend/issues"
homepage = "https://github.com/OCamlPro-Coquera/psmt2-frontend/"
archive = "https://github.com/OCamlPro-Coquera/psmt2-frontend/archive/0.3.tar.gz"

# keys that you could also define:
# build-profile = "...build-profile..."
# sphinx-target = "...sphinx-target..."

# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# github-organization = "...github-organization..."

[project]
description = """
An OCaml library to parse and type-check a conservative extension of the SMT-LIB 2
standard with prenex polymorphism.
"""

[drom]
skip = "license"

[dependencies]
[tools]
menhir= ""
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]
generators = ["ocamllex", "menhir"]
pack-modules = true
skip-dirs = []


[[package]]
dir = "src/bin"
kind = "program"
name = "psmt2-frontend_bin"
skeleton = "driver"
[package.dependencies]
psmt2-frontend = "version"

[[package]]
dir = "src/lib"
gen-version = "version.ml"
kind = "library"
name = "psmt2-frontend"
skeleton = "library"
pack = "Psmt2Frontend"

