language: c

env:
  global:
    - MPFR_VERSION="4.1.0"
    - MPFR_TARGZ="mpfr-$MPFR_VERSION.tar.gz"
    - MPFR_BUILD_DIR="/tmp"
  jobs:
    # default version
    - OCAML_VERSION="stable"
    # test a few more ocaml versions since 4.04.0
    - OCAML_VERSION="4.04.0"
    - OCAML_VERSION="4.07.0"

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo add-apt-repository ppa:ansible/bubblewrap -y && sudo apt-get update ; fi
  - wget https://www.mpfr.org/mpfr-$MPFR_VERSION/$MPFR_TARGZ

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install bubblewrap ; fi
  - yes /usr/local/bin | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)

before_script:
  - if [[ "$OCAML_VERSION" == "stable" ]];
    then opam init -a;
    else opam init --compiler=$OCAML_VERSION -a;
    fi
  - eval $(opam env)
  - opam install dune odoc -y
  - mv $MPFR_TARGZ $MPFR_BUILD_DIR
  - BUILD_DIR=`pwd`
  - cd $MPFR_BUILD_DIR
  - tar xvzf $MPFR_TARGZ
  - cd mpfr-$MPFR_VERSION
  - ./configure
  - make -j8
  - sudo make install
  - cd $BUILD_DIR

script:
  - dune build @install --profile dev
  - dune build @runtest --profile dev
  - dune build @doc
  - dune install
  # LD_LIBRARY_PATH is not exported by dune for executables
  # FIXME find a way to export LD_LIBRARY_PATH with dune
  - LD_LIBRARY_PATH=/usr/local/lib dune exec examples/example.exe
