name: Test
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        ocaml-compiler:
          - 4.11.x
          - 4.12.x
    steps:
      - uses: actions/checkout@v2
      - name: OCaml ${{ matrix.os }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}
          opam-depext-flags: --with-test
      - name: Install deps
        run: |
          opam pin add bytebuffer.dev -n .
          opam pin add h1_parser.dev -n .
          opam pin add h1.dev -n  .
          opam pin add h1_async.dev -n .
          opam install -t . --deps-only
      - name: Check build
        run: opam exec -- dune build @install
      - name: Run Test
        run: opam exec -- dune runtest
