language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
global: PACKAGE=polly
env:
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.08
os:
  - linux
