language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script:
  - bash -ex .travis-opam.sh

env:
  - OCAML_VERSION=4.03 PACKAGE=cuid UPDATE_GCC_BINUTILS=1
  - OCAML_VERSION=4.04 PACKAGE=cuid UPDATE_GCC_BINUTILS=1
  - OCAML_VERSION=4.05 PACKAGE=cuid UPDATE_GCC_BINUTILS=1
  - OCAML_VERSION=4.06 PACKAGE=cuid UPDATE_GCC_BINUTILS=1

os:
  - linux
  - osx
